config/routes.rb
Rails.application.routes.draw do
  
  resources :arrows
  resources :score_types

  resources :scores do 
    member do
      get 'puntuar'
      post 'puntuar'
      get 'add_arrow'
    end
  end

  mount Tolk::Engine => '/tolk', :as => 'tolk'
  devise_for :users

  root 'home#index'

   resources :android do
     collection do
       get 'acceso'
       post 'acceso'
       get 'getsesiones'
       post 'getsesiones'
    end
  end

  resources :home do
     collection do
       get 'index'
    end
  end

  resources :headers

end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :user
	belongs_to :score_type
	has_many   :arrows, dependent: :destroy
end

app/models/score_type.rb
class ScoreType < ActiveRecord::Base
	has_many :scores
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  layout 'app'
  before_action :authenticate_user!
  before_action :set_score, only: [:show, :edit, :update, :destroy, :puntuar, :add_arrow]

  def puntuar

  end

  def add_arrow
    value = params[:value].to_i
    Arrow.create(score_id: @score.id, value: value, arrow: params[:arrow])
    # acutalizamos datos del score
    @score.points += value
    @score.x_count += 1 if params[:arrow] == 'X'
    @score.ten_count += 1 if value == 10
    @score.x_count += 1 if value == 9
    @score.save
  end

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new(user_id: current_user)
    @score.points = @score.x_count = @score.ten_count = @score.nine_count = 0
    @score.average = 0.0
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to puntuar_score_path(@score), notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:name, :score_type_id, :user_id, :state, :published, :points, :average, :x_count, :ten_count, :nine_count)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_datos_parciales_score.html.erb
<div class="acenter">
	<h1>
		<div id="acumulacion" class="inline"><%= @score.points %></div>
		<div class="inline"><%= t 'score.points' %></div>
	</h1>
</div>

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score_type_id %><br>
    <%= f.number_field :score_type_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.number_field :published %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :average %><br>
    <%= f.text_field :average %>
  </div>
  <div class="field">
    <%= f.label :x_count %><br>
    <%= f.number_field :x_count %>
  </div>
  <div class="field">
    <%= f.label :ten_count %><br>
    <%= f.number_field :ten_count %>
  </div>
  <div class="field">
    <%= f.label :nine_count %><br>
    <%= f.number_field :nine_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/_keyboard.html.erb
<div class="keyboard">
	<div class="">
		<div class="arrow">
			<%= link_to 'X', add_arrow_score_path(@score, arrow:'X', value:10), class: 'btn btn-arrow', remote: true, 'data-value': 10, 'data-arrow': 'X' %>
		</div>
		<div class="arrow">
			<%= link_to '10', add_arrow_score_path(@score, arrow:'10', value:10), class: 'btn btn-arrow', remote: true, 'data-value': 10, 'data-arrow': '10' %>
		</div>
		<div class="arrow">
			<%= link_to '9', add_arrow_score_path(@score, arrow:'9', value:9), class: 'btn btn-arrow', remote: true, 'data-value': 9, 'data-arrow': '9' %>
		</div>
		<div class="arrow">
			<%= link_to '8', add_arrow_score_path(@score, arrow:'8', value:8), class: 'btn btn-arrow', remote: true, 'data-value': 8, 'data-arrow': '8' %>
		</div>
		<div class="arrow">
			<%= link_to '7', add_arrow_score_path(@score, arrow:'7', value:7), class: 'btn btn-arrow', remote: true, 'data-value': 7, 'data-arrow': '7' %>
		</div>
		<div class="arrow">
			<%= link_to '6', add_arrow_score_path(@score, arrow:'6', value:6), class: 'btn btn-arrow', remote: true, 'data-value': 6, 'data-arrow': '6' %>
		</div>
		<div class="arrow">
			<%= link_to '5', add_arrow_score_path(@score, arrow:'5', value:5), class: 'btn btn-arrow', remote: true, 'data-value': 5, 'data-arrow': '5' %>
		</div>
		<div class="arrow">
			<%= link_to '4', add_arrow_score_path(@score, arrow:'4', value:4), class: 'btn btn-arrow', remote: true, 'data-value': 4, 'data-arrow': '4' %>
		</div>
		<div class="arrow">
			<%= link_to '3', add_arrow_score_path(@score, arrow:'3', value:3), class: 'btn btn-arrow', remote: true, 'data-value': 3, 'data-arrow': '3' %>
		</div>
		<div class="arrow">
			<%= link_to '2', add_arrow_score_path(@score, arrow:'2', value:2), class: 'btn btn-arrow', remote: true, 'data-value': 2, 'data-arrow': '2' %>
		</div>
		<div class="arrow">
			<%= link_to '1', add_arrow_score_path(@score, arrow:'1', value:1), class: 'btn btn-arrow', remote: true, 'data-value': 1, 'data-arrow': '1' %>
		</div>
		<div class="arrow">
			<%= link_to 'M', add_arrow_score_path(@score, arrow:'M', value:0), class: 'btn btn-arrow', remote: true, 'data-value': 0, 'data-arrow': 'M' %>
		</div>
	</div>
</div>

<script>
	var foco = 1;
	$('.btn-arrow').click(function(){
		var value = $(this).data('value');
		var arrow = $(this).data('arrow');
		$('#acumulacion').html(parseInt($('#acumulacion').html())+value);
		$('#arrow_'+foco).val(arrow);
		suma_parcial(value);
		foco++;
		if(foco>6) {
			foco=1;
			setTimeout(function(){
			    //do what you need here
				$('.parciales').val(null);
				$('.suma_parcial').val(0);
			}, 2000);
		}
	});

	function suma_parcial(value) {
		if(foco < 4) {
			$('#partial_1').val(parseInt($('#partial_1').val())+value);	
		}else{
			$('#partial_2').val(parseInt($('#partial_2').val())+value);
		}
	}
</script>

app/views/scores/_partial_score.html.erb
<div class="partial_score">
	<div class="">
		<div class="arrow">
			<%= text_field_tag "arrow_1",'', id: 'arrow_1', class: 'parciales' %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_2",'', id: 'arrow_2', class: 'parciales' %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_3",'', id: 'arrow_3', class: 'parciales' %>
		</div>
		<div class="arrow">
			<%= text_field_tag "partial_1",'0', id: 'partial_1', class: 'suma_parcial' %>
		</div>
	</div>
	<div class="">
		<div class="arrow">
			<%= text_field_tag "arrow_4",'', id: 'arrow_4', class: 'parciales' %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_5",'', id: 'arrow_5', class: 'parciales' %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_6",'', id: 'arrow_6', class: 'parciales' %>
		</div>
		<div class="arrow">
			<%= text_field_tag "partial_2",'0', id: 'partial_2', class: 'suma_parcial' %>
		</div>
	</div>
</div>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Score type</th>
      <th>User</th>
      <th>State</th>
      <th>Published</th>
      <th>Points</th>
      <th>Average</th>
      <th>X count</th>
      <th>Ten count</th>
      <th>Nine count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.name %></td>
        <td><%= score.score_type_id %></td>
        <td><%= score.user_id %></td>
        <td><%= score.state %></td>
        <td><%= score.published %></td>
        <td><%= score.points %></td>
        <td><%= score.average %></td>
        <td><%= score.x_count %></td>
        <td><%= score.ten_count %></td>
        <td><%= score.nine_count %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/puntuar.html.erb
<%= render 'scores/datos_parciales_score' %>
<%= render 'scores/partial_score' %>
<%= render 'scores/keyboard' %>

app/views/scores/puntuar.js.erb
puntuar.js.erb

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @score.name %>
</p>

<p>
  <strong>Score type:</strong>
  <%= @score.score_type_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @score.user_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @score.state %>
</p>

<p>
  <strong>Published:</strong>
  <%= @score.published %>
</p>

<p>
  <strong>Points:</strong>
  <%= @score.points %>
</p>

<p>
  <strong>Average:</strong>
  <%= @score.average %>
</p>

<p>
  <strong>X count:</strong>
  <%= @score.x_count %>
</p>

<p>
  <strong>Ten count:</strong>
  <%= @score.ten_count %>
</p>

<p>
  <strong>Nine count:</strong>
  <%= @score.nine_count %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>