config/routes.rb
Rails.application.routes.draw do
  
  resources :arrows
  resources :score_types

  resources :scores do 
    member do
      get 'puntuar'
      post 'puntuar'
      get 'add_arrow'
    end
  end

  mount Tolk::Engine => '/tolk', :as => 'tolk'
  devise_for :users

  root 'home#index'

   resources :android do
     collection do
       get 'acceso'
       post 'acceso'
       get 'getsesiones'
       post 'getsesiones'
    end
  end

  resources :home do
     collection do
       get 'index'
    end
  end

  resources :headers

end

app/models/header.rb
class Header < ActiveRecord::Base
	has_attached_file :photo, styles: { hight: "1000x1000>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  	validates :title, :photo, presence: true
end

app/controllers/headers_controller.rb
class HeadersController < ApplicationController

  before_action :authenticate_user!
  
  before_action :set_header, only: [:show, :edit, :update, :destroy]
  before_action :set_controllers, only: [:edit, :new]

  respond_to :html

  def index
    @headers = Header.all
    respond_with(@headers)
  end

  def show
    respond_with(@header)
  end

  def new
    @header = Header.new
    respond_with(@header)
  end

  def edit
  end

  def create
    @header = Header.new(header_params)
    @header.save
    respond_with(@header)
  end

  def update
    @header.update(header_params)
    respond_with(@header)
  end

  def destroy
    @header.destroy
    respond_with(@header)
  end

  private
    def set_controllers
      Rails.application.eager_load!
      @controllers = ApplicationController.descendants
    end
    
    def set_header
      @header = Header.find(params[:id])
    end

    def header_params
      params.require(:header).permit(:title, :description, :photo, :used_at)
    end
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/views/headers/_form.html.erb
<%= form_for(@header, html: { multipart: true }) do |f| %>
  <% if @header.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@header.errors.count, "error") %> prohibited this header from being saved:</h2>

      <ul>
      <% @header.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :used_at %><br>
    <%= f.select :used_at, options_for_select(@controllers) %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/headers/_gallery_header.html.erb
<% header = Header.last %>
<% if header.blank? %>
	<header>
<% else %>
	<header style="background-image: url('<%= header.photo.url %>');">
<% end %>
    <div class="container">
        <div class="intro-text gallery">
            <div class="intro-lead-in"><%= header.description %></div>
            <!--<a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>-->
        </div>
    </div>
</header>

app/views/headers/_header.html.erb
<% if @header.blank? %>
    <header>
<% else %>
    <header style="background-image: url('<%= @header.photo.url %>');">
<% end %>
    <div class="shadow-layer">
        <div class="header-content">
            <div class="header-content-inner">
                <h1><%= @header.title %></h1>
                <hr>
                <p><%= @header.description %></p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll"><%= t 'home.header.boton_mas' %></a>
            </div>
        </div>
    </div>
</header>

app/views/headers/edit.html.erb
<h1>Editing header</h1>

<%= render 'form' %>

<%= link_to 'Show', @header %> |
<%= link_to 'Back', headers_path %>

app/views/headers/index.html.erb
<h1>Listing headers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @headers.each do |header| %>
      <tr>
        <td><%= header.title %></td>
        <td><%= header.description %></td>
        <td><%= image_tag header.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', header %></td>
        <td><%= link_to 'Edit', edit_header_path(header) %></td>
        <td><%= link_to 'Destroy', header, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Header', new_header_path %>

app/views/headers/new.html.erb
<h1>New header</h1>

<%= render 'form' %>

<%= link_to 'Back', headers_path %>

app/views/headers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @header.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @header.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @header.photo.url(:medium) %>
</p>

<%= link_to 'Edit', edit_header_path(@header) %> |
<%= link_to 'Back', headers_path %>